import { UserProfile, FoodListing, FoodClaim, UserNotification, AuditLog } from '@/lib/types';

export const initialProfiles: UserProfile[] = [
  {
    id: 'usr-admin-01',
    email: 'admin@sharebytes.org',
    role: 'admin',
    full_name: 'Platform Administrator',
    phone: '+91 98765 00000',
    business_name: 'ShareBytes Admin HQ',
    address: 'Central Tech Hub, Chennai',
    verified_status: 'verified',
    created_at: new Date().toISOString(),
    demo_password: 'demo1234',
  },
  {
    id: 'usr-rest-01',
    email: 'bakery@goldenharvest.com',
    role: 'restaurant',
    full_name: 'Golden Harvest Bakery',
    phone: '+91 98765 11111',
    business_name: 'Golden Harvest Bakery & Cafe',
    address: '42 MG Road, Downtown Chennai',
    fssai_cert_url: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=500&auto=format&fit=crop&q=60',
    entity_photo_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=60',
    verified_status: 'verified',
    created_at: new Date().toISOString(),
    demo_password: 'demo1234',
  },
  {
    id: 'usr-rest-02',
    email: 'bistro@greenearth.com',
    role: 'restaurant',
    full_name: 'Green Earth Organics',
    phone: '+91 98765 22222',
    business_name: 'Green Earth Organic Bistro',
    address: '88 Anna Salai, T. Nagar, Chennai',
    fssai_cert_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=500&auto=format&fit=crop&q=60',
    entity_photo_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500&auto=format&fit=crop&q=60',
    verified_status: 'pending',
    created_at: new Date().toISOString(),
    demo_password: 'demo1234',
  },
  {
    id: 'usr-donor-01',
    email: 'donor@anandcaterers.com',
    role: 'food_donor',
    full_name: 'Anand Caterers',
    phone: '+91 98765 33333',
    business_name: 'Anand Event & Banquet Caterers',
    address: '15 Grand Hall Road, Velachery, Chennai',
    entity_photo_url: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=500&auto=format&fit=crop&q=60',
    verified_status: 'verified',
    created_at: new Date().toISOString(),
    demo_password: 'demo1234',
  },
  {
    id: 'usr-ngo-01',
    email: 'ngo@stjude.org',
    role: 'ngo',
    full_name: 'St. Jude Community Shelter',
    phone: '+91 98765 44444',
    business_name: 'St. Jude Shelter & Hope Trust',
    address: '102 Hope Avenue, Mylapore, Chennai',
    registration_cert_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=500&auto=format&fit=crop&q=60',
    entity_photo_url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=500&auto=format&fit=crop&q=60',
    verified_status: 'verified',
    created_at: new Date().toISOString(),
    demo_password: 'demo1234',
  },
  {
    id: 'usr-ngo-02',
    email: 'ngo@hopehaven.org',
    role: 'ngo',
    full_name: 'Hope Haven Foundation',
    phone: '+91 98765 55555',
    business_name: 'Hope Haven Children Trust',
    address: '77 Peace Colony, Adyar, Chennai',
    registration_cert_url: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=500&auto=format&fit=crop&q=60',
    entity_photo_url: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=500&auto=format&fit=crop&q=60',
    verified_status: 'pending',
    created_at: new Date().toISOString(),
    demo_password: 'demo1234',
  },
  {
    id: 'usr-cust-01',
    email: 'customer@gmail.com',
    role: 'customer',
    full_name: 'Rahul Sharma',
    phone: '+91 98765 66666',
    address: 'Flat 4B, Emerald Heights, Chennai',
    verified_status: 'verified',
    created_at: new Date().toISOString(),
    demo_password: 'demo1234',
  },
];

export const initialListings: FoodListing[] = [
  {
    id: 'lst-01',
    title: 'Fresh Artisan Sourdough & Brioche Trays',
    description: 'Crispy oven-fresh sourdough loaves and butter brioche buns baked this morning.',
    food_type: 'veg',
    portion_count: 15,
    original_price: 350,
    discounted_price: 90,
    is_donation_only: false,
    expiry_time: new Date(Date.now() + 4 * 3600 * 1000).toISOString(),
    ngo_priority_until: new Date(Date.now() + 45 * 60 * 1000).toISOString(), // 45 min left
    delivery_available: true,
    pickup_location: 'Golden Harvest Bakery, 42 MG Road, Downtown Chennai',
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=60',
    status: 'available',
    created_by: 'usr-rest-01',
    role_type: 'restaurant',
    creator_name: 'Golden Harvest Bakery',
    creator_business: 'Golden Harvest Bakery & Cafe',
    created_at: new Date().toISOString(),
  },
  {
    id: 'lst-02',
    title: 'Fresh Catering Surplus Meals (Veg Dum Biryani)',
    description: 'Hot fragrant Hyderabadi vegetable dum biryani served with raita and mirchi ka salan from afternoon banquet.',
    food_type: 'veg',
    portion_count: 40,
    original_price: 0,
    discounted_price: 0,
    is_donation_only: true,
    expiry_time: new Date(Date.now() + 3 * 3600 * 1000).toISOString(),
    ngo_priority_until: new Date(Date.now() + 55 * 60 * 1000).toISOString(), // 55 min left
    delivery_available: true,
    pickup_location: 'Anand Caterers, 15 Grand Hall Road, Velachery',
    image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=60',
    status: 'available',
    created_by: 'usr-donor-01',
    role_type: 'food_donor',
    creator_name: 'Anand Caterers',
    creator_business: 'Anand Event & Banquet Caterers',
    created_at: new Date().toISOString(),
  },
  {
    id: 'lst-03',
    title: 'Whole Wheat Paneer Paratha & Chole Trays',
    description: 'Warm stuffed paneer parathas paired with rich Punjabi chole curry.',
    food_type: 'veg',
    portion_count: 20,
    original_price: 240,
    discounted_price: 60,
    is_donation_only: false,
    expiry_time: new Date(Date.now() + 5 * 3600 * 1000).toISOString(),
    delivery_available: true,
    pickup_location: 'Green Earth Bistro, 88 Anna Salai, T. Nagar',
    image_url: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=60',
    status: 'available',
    created_by: 'usr-rest-02',
    role_type: 'restaurant',
    creator_name: 'Green Earth Organics',
    creator_business: 'Green Earth Organic Bistro',
    created_at: new Date().toISOString(),
  },
  {
    id: 'lst-04',
    title: 'Organic Garden Salad & Pasta Meal Boxes',
    description: 'Nutritious penne pasta in arrabbiata sauce with crisp garden salad side.',
    food_type: 'veg',
    portion_count: 25,
    original_price: 300,
    discounted_price: 75,
    is_donation_only: false,
    expiry_time: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
    delivery_available: false,
    pickup_location: 'Golden Harvest Bakery, 42 MG Road, Downtown Chennai',
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=60',
    status: 'available',
    created_by: 'usr-rest-01',
    role_type: 'restaurant',
    creator_name: 'Golden Harvest Bakery',
    creator_business: 'Golden Harvest Bakery & Cafe',
    created_at: new Date().toISOString(),
  },
  {
    id: 'lst-05',
    title: 'Surplus Banquet Fruit Bowls & Custard Cups',
    description: 'Fresh seasonal sliced melons, pineapples, berries, and vanilla custard cups.',
    food_type: 'veg',
    portion_count: 30,
    original_price: 0,
    discounted_price: 0,
    is_donation_only: true,
    expiry_time: new Date(Date.now() + 2 * 3600 * 1000).toISOString(),
    delivery_available: true,
    pickup_location: 'Anand Caterers, Velachery Hall',
    image_url: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=600&auto=format&fit=crop&q=60',
    status: 'available',
    created_by: 'usr-donor-01',
    role_type: 'food_donor',
    creator_name: 'Anand Caterers',
    creator_business: 'Anand Event & Banquet Caterers',
    created_at: new Date().toISOString(),
  },
];

export const initialClaims: FoodClaim[] = [
  {
    id: 'clm-01',
    listing_id: 'lst-02',
    claimed_by: 'usr-ngo-01',
    portion_count: 30,
    status: 'pending',
    payment_method: 'cash_on_pickup',
    delivery_requested: true,
    created_at: new Date(Date.now() - 1800 * 1000).toISOString(),
  },
  {
    id: 'clm-02',
    listing_id: 'lst-01',
    claimed_by: 'usr-cust-01',
    portion_count: 3,
    status: 'accepted',
    payment_method: 'cash_on_pickup',
    delivery_requested: false,
    created_at: new Date(Date.now() - 3600 * 1000).toISOString(),
  },
];

export const initialNotifications: UserNotification[] = [
  {
    id: 'ntf-01',
    user_id: 'usr-ngo-01',
    title: 'New Donation Batch Nearby',
    message: 'Anand Caterers posted 40 portions of Veg Dum Biryani.',
    read: false,
    link: '/dashboard/ngo',
    created_at: new Date(Date.now() - 2000 * 1000).toISOString(),
  },
  {
    id: 'ntf-02',
    user_id: 'usr-rest-01',
    title: 'Claim Accepted',
    message: 'Rahul Sharma reserved 3 sourdough portions.',
    read: true,
    link: '/dashboard/restaurant',
    created_at: new Date(Date.now() - 4000 * 1000).toISOString(),
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'aud-01',
    actor_id: 'usr-admin-01',
    action: 'VERIFIED_USER',
    target: 'Golden Harvest Bakery',
    details: { role: 'restaurant', status: 'verified' },
    created_at: new Date(Date.now() - 86400 * 1000).toISOString(),
    actor_email: 'admin@sharebytes.org',
  },
  {
    id: 'aud-02',
    actor_id: 'usr-admin-01',
    action: 'VERIFIED_USER',
    target: 'St. Jude Shelter Trust',
    details: { role: 'ngo', status: 'verified' },
    created_at: new Date(Date.now() - 43200 * 1000).toISOString(),
    actor_email: 'admin@sharebytes.org',
  },
];
